<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Allan Omondi" />

<meta name="date" content="2025-04-27" />

<title>Simple Linear Regression</title>

<script src="1_simple_linear_regression_files/header-attrs-2.29/header-attrs.js"></script>
<script src="1_simple_linear_regression_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="1_simple_linear_regression_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="1_simple_linear_regression_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="1_simple_linear_regression_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="1_simple_linear_regression_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="1_simple_linear_regression_files/navigation-1.1/tabsets.js"></script>
<link href="1_simple_linear_regression_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="1_simple_linear_regression_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div id="header">



<h1 class="title toc-ignore">Simple Linear Regression</h1>
<h4 class="author">Allan Omondi</h4>
<h4 class="date">2025-04-27</h4>

</div>

<div id="TOC">
<ul>
<li><a href="#load-the-dataset" id="toc-load-the-dataset"><span
class="toc-section-number">1</span> Load the Dataset</a></li>
<li><a href="#initial-exploratory-data-analysis-eda"
id="toc-initial-exploratory-data-analysis-eda"><span
class="toc-section-number">2</span> Initial Exploratory Data Analysis
(EDA)</a>
<ul>
<li><a href="#measures-of-frequency"
id="toc-measures-of-frequency"><span
class="toc-section-number">2.1</span> <u><strong>Measures of
Frequency</strong></u></a></li>
<li><a href="#measures-of-central-tendency"
id="toc-measures-of-central-tendency"><span
class="toc-section-number">2.2</span> <u><strong>Measures of Central
Tendency</strong></u></a></li>
<li><a href="#measures-of-distribution"
id="toc-measures-of-distribution"><span
class="toc-section-number">2.3</span> <u><strong>Measures of
Distribution</strong></u></a></li>
<li><a href="#measures-of-relationship"
id="toc-measures-of-relationship"><span
class="toc-section-number">2.4</span> <u><strong>Measures of
Relationship</strong></u></a></li>
<li><a href="#basic-visualizations" id="toc-basic-visualizations"><span
class="toc-section-number">2.5</span> <u><strong>Basic
Visualizations</strong></u></a>
<ul>
<li><a href="#histogram" id="toc-histogram"><span
class="toc-section-number">2.5.1</span>
<strong>Histogram</strong></a></li>
<li><a href="#box-and-whisker-plot" id="toc-box-and-whisker-plot"><span
class="toc-section-number">2.5.2</span> <strong>Box and Whisker
Plot</strong></a></li>
<li><a href="#missing-data-plot" id="toc-missing-data-plot"><span
class="toc-section-number">2.5.3</span> <strong>Missing Data
Plot</strong></a></li>
<li><a href="#correlation-plot" id="toc-correlation-plot"><span
class="toc-section-number">2.5.4</span> <strong>Correlation
Plot</strong></a></li>
<li><a href="#scatter-plot" id="toc-scatter-plot"><span
class="toc-section-number">2.5.5</span> <strong>Scatter
Plot</strong></a></li>
</ul></li>
</ul></li>
<li><a href="#statistical-test" id="toc-statistical-test"><span
class="toc-section-number">3</span> Statistical Test</a></li>
<li><a href="#diagnostic-eda" id="toc-diagnostic-eda"><span
class="toc-section-number">4</span> Diagnostic EDA</a>
<ul>
<li><a href="#test-of-linearity" id="toc-test-of-linearity"><span
class="toc-section-number">4.1</span> <u><strong>Test of
Linearity</strong></u></a></li>
<li><a href="#test-of-independence-of-errors"
id="toc-test-of-independence-of-errors"><span
class="toc-section-number">4.2</span> <u><strong>Test of Independence of
Errors</strong></u></a></li>
<li><a href="#test-of-normality" id="toc-test-of-normality"><span
class="toc-section-number">4.3</span> <u><strong>Test of
Normality</strong></u></a></li>
<li><a href="#test-of-homoscedasticity"
id="toc-test-of-homoscedasticity"><span
class="toc-section-number">4.4</span> <u><strong>Test of
Homoscedasticity</strong></u></a></li>
<li><a href="#quantitative-validation-of-assumptions"
id="toc-quantitative-validation-of-assumptions"><span
class="toc-section-number">4.5</span> <u><strong>Quantitative Validation
of Assumptions</strong></u></a></li>
</ul></li>
<li><a href="#interpret-the-results"
id="toc-interpret-the-results"><span class="toc-section-number">5</span>
Interpret the Results</a>
<ul>
<li><a href="#academic-statement" id="toc-academic-statement"><span
class="toc-section-number">5.1</span> Academic Statement</a></li>
<li><a href="#business-analysis" id="toc-business-analysis"><span
class="toc-section-number">5.2</span> Business Analysis</a></li>
</ul></li>
</ul>
</div>

<div id="load-the-dataset" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Load the Dataset</h1>
<p>The following synthetic dataset contains the estimated Customer
Lifetime Value (CLV) as the dependent variable and the customer purchase
frequency as the independent variable. The dataset is loaded as shown
below.</p>
<pre class="r"><code># `pacman::p_load()` is designed to both install and load packages
pacman::p_load(&quot;readr&quot;)

clv_data &lt;- read_csv(&quot;./data/clv_data.csv&quot;)
head(clv_data)</code></pre>
<pre><code>## # A tibble: 6 × 2
##   purchase_frequency customer_lifetime_value
##                &lt;dbl&gt;                   &lt;dbl&gt;
## 1                  3                   110. 
## 2                  7                   190. 
## 3                  6                   160. 
## 4                  2                    94.4
## 5                  4                   133. 
## 6                  8                   223.</code></pre>
<p>Display a summary of all the variables.</p>
<pre class="r"><code>summary(clv_data)</code></pre>
<pre><code>##  purchase_frequency customer_lifetime_value
##  Min.   :-1.000     Min.   : 26.13         
##  1st Qu.: 4.000     1st Qu.:122.04         
##  Median : 5.000     Median :148.21         
##  Mean   : 4.914     Mean   :148.25         
##  3rd Qu.: 6.000     3rd Qu.:175.88         
##  Max.   :11.000     Max.   :262.04</code></pre>
</div>
<div id="initial-exploratory-data-analysis-eda" class="section level1"
number="2">
<h1><span class="header-section-number">2</span> Initial Exploratory
Data Analysis (EDA)</h1>
<p><u><strong>View the Dimensions</strong></u></p>
<p>The number of observations and the number of variables.</p>
<pre class="r"><code>dim(clv_data)</code></pre>
<pre><code>## [1] 500   2</code></pre>
<p><u><strong>View the Data Types</strong></u></p>
<pre class="r"><code>sapply(clv_data, class)</code></pre>
<pre><code>##      purchase_frequency customer_lifetime_value 
##               &quot;numeric&quot;               &quot;numeric&quot;</code></pre>
<pre class="r"><code>str(clv_data)</code></pre>
<pre><code>## spc_tbl_ [500 × 2] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ purchase_frequency     : num [1:500] 3 7 6 2 4 8 0 4 8 3 ...
##  $ customer_lifetime_value: num [1:500] 110.3 190.2 160 94.4 133.2 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   purchase_frequency = col_double(),
##   ..   customer_lifetime_value = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<p><u><strong>Descriptive Statistics</strong></u></p>
<p>Understanding your data can lead to:</p>
<ul>
<li><p><strong>Data cleaning:</strong> To remove extreme outliers or
impute missing data.</p></li>
<li><p><strong>Data transformation:</strong> To reduce skewness</p></li>
<li><p><strong>Data modelling:</strong> You may notice properties of the
data such as distributions or data types that suggest the use of
parametric or non-parametric statistical tests and algorithms</p></li>
</ul>
<p>Descriptive statistics can be used to understand your data. Typical
descriptive statistics include:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Measures of frequency:</strong> count and
percent</p></li>
<li><p><strong>Measures of central tendency:</strong> mean, median, and
mode</p></li>
<li><p><strong>Measures of
distribution/dispersion/spread/scatter/variability:</strong> minimum,
quartiles, maximum, variance, standard deviation, coefficient of
variation, range, interquartile range (IQR) [includes a box and whisker
plot for visualization], kurtosis, skewness [includes a histogram for
visualization]).</p></li>
<li><p><strong>Measures of relationship:</strong> covariance and
correlation</p></li>
</ol>
<div id="measures-of-frequency" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> <u><strong>Measures
of Frequency</strong></u></h2>
<p>This is applicable in cases where you have categorical variables,
e.g., 60% of the observations are male and 40% are female (2
categories).</p>
</div>
<div id="measures-of-central-tendency" class="section level2"
number="2.2">
<h2><span class="header-section-number">2.2</span> <u><strong>Measures
of Central Tendency</strong></u></h2>
<p>The median and the mean of each numeric varible:</p>
<pre class="r"><code>summary(clv_data)</code></pre>
<pre><code>##  purchase_frequency customer_lifetime_value
##  Min.   :-1.000     Min.   : 26.13         
##  1st Qu.: 4.000     1st Qu.:122.04         
##  Median : 5.000     Median :148.21         
##  Mean   : 4.914     Mean   :148.25         
##  3rd Qu.: 6.000     3rd Qu.:175.88         
##  Max.   :11.000     Max.   :262.04</code></pre>
</div>
<div id="measures-of-distribution" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> <u><strong>Measures
of Distribution</strong></u></h2>
<p>Measuring the variability in the dataset is important because the
amount of variability determines <strong>how well you can
generalize</strong> results from the sample to a new observation in the
population.</p>
<p>Low variability is ideal because it means that you can better predict
information about the population based on the sample data. High
variability means that the values are less consistent, thus making it
harder to make predictions.</p>
<p>The format <code>dataset[rows, columns]</code> can be used to specify
the exact rows and columns to be considered.
<code>dataset[, columns]</code> implies all rows will be considered.
Specifying <code>BostonHousing[, -4]</code> implies all the columns
except column number 4. This can also be stated as
<code>BostonHousing[, c(1,2,3,5,6,7,8,9,10,11,12,13,14)]</code>. This
allows us to calculate the standard deviation of only columns that are
numeric, thus leaving out the columns termed as “factors” (categorical)
or those that have a string data type.</p>
<p><strong>Variance:</strong></p>
<pre class="r"><code># `sapply()` is designed to apply a function to a variable in a dataset
# In this case, we use `sapply()` to apply the `var()` function used to compute the variance.
sapply(clv_data[,], var)</code></pre>
<pre><code>##      purchase_frequency customer_lifetime_value 
##                4.146898             1642.315996</code></pre>
<p><strong>Standard deviation:</strong></p>
<pre class="r"><code>sapply(clv_data[,], sd)</code></pre>
<pre><code>##      purchase_frequency customer_lifetime_value 
##                2.036393               40.525498</code></pre>
<p><strong>Kurtosis:</strong></p>
<p>The Kurtosis informs us of how often outliers occur in the results.
There are different formulas for calculating kurtosis. Specifying “type
= 2” allows us to use the 2nd formula which is the same kurtosis formula
used in other statistical software like SPSS and SAS.</p>
<p>In “type = 2” (used in SPSS and SAS):</p>
<ol style="list-style-type: decimal">
<li><p>Kurtosis &lt; 3 implies a low number of outliers</p></li>
<li><p>Kurtosis = 3 implies a medium number of outliers</p></li>
<li><p>Kurtosis &gt; 3 implies a high number of outliers</p></li>
</ol>
<pre class="r"><code>pacman::p_load(&quot;e1071&quot;)
sapply(clv_data[,],  kurtosis, type = 2)</code></pre>
<pre><code>##      purchase_frequency customer_lifetime_value 
##              -0.1220038              -0.1484811</code></pre>
<p><strong>Skewness:</strong></p>
<p>The skewness is used to identify the asymmetry of the distribution of
results. Similar to kurtosis, there are several ways of computing the
skewness.</p>
<p>Using “type = 2” (common in other statistical software like SPSS and
SAS) can be interpreted as:</p>
<ol style="list-style-type: decimal">
<li><p>Skewness between -0.4 and 0.4 (inclusive) implies that there is
no skew in the distribution of results; the distribution of results is
symmetrical; it is a normal distribution; a Gaussian
distribution.</p></li>
<li><p>Skewness above 0.4 implies a positive skew; a right-skewed
distribution.</p></li>
<li><p>Skewness below -0.4 implies a negative skew; a left-skewed
distribution.</p></li>
</ol>
<pre class="r"><code>sapply(clv_data[,], skewness, type = 2)</code></pre>
<pre><code>##      purchase_frequency customer_lifetime_value 
##             -0.04021915             -0.01608242</code></pre>
</div>
<div id="measures-of-relationship" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> <u><strong>Measures
of Relationship</strong></u></h2>
<p><strong>Covariance:</strong></p>
<p>Covariance is a statistical measure that indicates the direction of
the linear relationship between two variables. It assesses whether
increases in one variable correspond to increases or decreases in
another.​</p>
<ul>
<li><p><strong>Positive Covariance:</strong> When one variable
increases, the other tends to increase as well.</p></li>
<li><p><strong>Negative Covariance:</strong> When one variable
increases, the other tends to decrease.</p></li>
<li><p><strong>Zero Covariance:</strong> No linear relationship exists
between the variables.</p></li>
</ul>
<p>While covariance indicates the direction of a relationship, it does
not convey the strength or consistency of the relationship. The
correlation coefficient is used to indicate the strength of the
relationship.</p>
<pre class="r"><code>cov(clv_data, method = &quot;spearman&quot;)</code></pre>
<pre><code>##                         purchase_frequency customer_lifetime_value
## purchase_frequency                20409.91                20235.73
## customer_lifetime_value           20235.73                20874.99</code></pre>
<p><strong>Correlation:</strong></p>
<p>A strong correlation between variables enables us to better predict
the value of the dependent variable using the value of the independent
variable. However, a weak correlation between two variables does not
help us to predict the value of the dependent variable from the value of
the independent variable. This is useful only if there is a linear
association between the variables.</p>
<p>We can measure the statistical significance of the correlation using
Spearman’s rank correlation <em>rho</em>. This shows us if the variables
are significantly monotonically related. A monotonic relationship
between two variables implies that as one variable increases, the other
variable either consistently increases or consistently decreases. The
key characteristic is the preservation of the direction of change,
though the rate of change may vary.</p>
<pre class="r"><code>cor.test(clv_data$customer_lifetime_value, clv_data$purchase_frequency, method = &quot;spearman&quot;)</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  clv_data$customer_lifetime_value and clv_data$purchase_frequency
## S = 409190, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.9803588</code></pre>
<p>To view the correlation of all variables</p>
<pre class="r"><code>cor(clv_data, method = &quot;spearman&quot;)</code></pre>
<pre><code>##                         purchase_frequency customer_lifetime_value
## purchase_frequency               1.0000000               0.9803588
## customer_lifetime_value          0.9803588               1.0000000</code></pre>
</div>
<div id="basic-visualizations" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> <u><strong>Basic
Visualizations</strong></u></h2>
<div id="histogram" class="section level3" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span>
<strong>Histogram</strong></h3>
<pre class="r"><code># `par(mfrow = c(1, 2))` This is used to divide the area used to plot the visualization into a 1 row by 2 columns grid
# `for (i in 1:2)` This is used to identify the variable (column) that is being processed
# `clv_data[[i]]` This is used to extract the i-th column as a vector
# `hist()` This is the function used to plot the histogram
par(mfrow = c(1, 2))
for (i in 1:2) {
  if (is.numeric(clv_data[[i]])) {
    hist(clv_data[[i]],
         main = names(clv_data)[i],
         xlab = names(clv_data)[i])
  } else {
    message(paste(&quot;Column&quot;, names(clv_data)[i], &quot;is not numeric and will be skipped.&quot;))
  }
}</code></pre>
<p><img
src="1_simple_linear_regression_files/figure-html/visualization_histogram-1.png" /><!-- --></p>
</div>
<div id="box-and-whisker-plot" class="section level3" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> <strong>Box and
Whisker Plot</strong></h3>
<pre class="r"><code># `boxplot()` This is the function used to plot the box and whisker plot visualization
par(mfrow = c(1, 2))
for (i in 1:2) {
  if (is.numeric(clv_data[[i]])) {
    boxplot(clv_data[[i]], main = names(clv_data)[i])
  } else {
    message(paste(&quot;Column&quot;, names(clv_data)[i], &quot;is not numeric and will be skipped.&quot;))
  }
}</code></pre>
<p><img
src="1_simple_linear_regression_files/figure-html/visualization_boxplot-1.png" /><!-- --></p>
</div>
<div id="missing-data-plot" class="section level3" number="2.5.3">
<h3><span class="header-section-number">2.5.3</span> <strong>Missing
Data Plot</strong></h3>
<pre class="r"><code>pacman::p_load(&quot;Amelia&quot;)

missmap(clv_data, col = c(&quot;red&quot;, &quot;grey&quot;), legend = TRUE)</code></pre>
<p><img
src="1_simple_linear_regression_files/figure-html/missing_data_plot-1.png" /><!-- --></p>
</div>
<div id="correlation-plot" class="section level3" number="2.5.4">
<h3><span class="header-section-number">2.5.4</span> <strong>Correlation
Plot</strong></h3>
<pre class="r"><code>pacman::p_load(&quot;ggcorrplot&quot;)

ggcorrplot(cor(clv_data[,]))</code></pre>
<p><img
src="1_simple_linear_regression_files/figure-html/correlation_plot-1.png" /><!-- --></p>
</div>
<div id="scatter-plot" class="section level3" number="2.5.5">
<h3><span class="header-section-number">2.5.5</span> <strong>Scatter
Plot</strong></h3>
<pre class="r"><code>pacman::p_load(&quot;corrplot&quot;)

pairs(clv_data$customer_lifetime_value ~ ., data = clv_data, col = clv_data$customer_lifetime_value)</code></pre>
<p><img
src="1_simple_linear_regression_files/figure-html/scatter_plot_1-1.png" /><!-- --></p>
<pre class="r"><code>pacman::p_load(&quot;ggplot2&quot;)
ggplot(clv_data,
       aes(x = purchase_frequency, y = customer_lifetime_value)) + 
  geom_point() +
  geom_smooth(method = lm) +
  labs(
    title = &quot;Relationship between Customer Lifetime Value and Purchase Frequency&quot;,
    x = &quot;Purchase Frequency&quot;,
    y = &quot;Customer Lifetime Value&quot;
  )</code></pre>
<p><img
src="1_simple_linear_regression_files/figure-html/scatter_plot_2-1.png" /><!-- --></p>
</div>
</div>
</div>
<div id="statistical-test" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Statistical Test</h1>
<p>We then apply a simple linear regression as a statistical test for
regression.</p>
<p>View the summary of the model.</p>
<pre class="r"><code>summary(slr_test)</code></pre>
<pre><code>## 
## Call:
## lm(formula = customer_lifetime_value ~ purchase_frequency, data = clv_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -19.1176  -5.6169  -0.0491   5.6618  20.4837 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         52.2538     0.9042   57.79   &lt;2e-16 ***
## purchase_frequency  19.5356     0.1700  114.91   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.734 on 498 degrees of freedom
## Multiple R-squared:  0.9637, Adjusted R-squared:  0.9636 
## F-statistic: 1.32e+04 on 1 and 498 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="diagnostic-eda" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Diagnostic EDA</h1>
<p>Diagnostic EDA is performed to validate that the regression
assumptions are true with respect to the statistical test. Validating
the regression assumption in turn ensures that the statistical tests
applied are appropriate for the data and helps to prevent incorrect
conclusions.</p>
<div id="test-of-linearity" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> <u><strong>Test of
Linearity</strong></u></h2>
<p>The test of lineary is used to assess whether the relationship
between the dependent variables and the independent variables is linear.
This is necessary given that linearity is one of the key assumptions of
linear regression models and verifying it is crucial for ensuring the
validity of the model’s estimates and predictions.</p>
<p>A plot of the residuals versus the fitted values enables us to test
for linearity. For the model to pass the test of linearity, there should
be no pattern in the distribution of residuals and the residuals should
be randomly placed around the 0.0 residual line, i.e., the residuals
should randomly vary around the mean of the value of the response
variable.</p>
<pre class="r"><code>plot(slr_test, which = 1)</code></pre>
<p><img
src="1_simple_linear_regression_files/figure-html/test_of_linearity-1.png" /><!-- --></p>
</div>
<div id="test-of-independence-of-errors" class="section level2"
number="4.2">
<h2><span class="header-section-number">4.2</span> <u><strong>Test of
Independence of Errors</strong></u></h2>
<p>This test is necessary to confirm that each observation is
independent of the other. It helps to identify
<strong>autocorrelation</strong> that is introduced when the data is
collected over a close period of time or when one observation is related
to another observation. Autocorrelation leads to underestimated standard
errors and inflated t-statistics. It can also make findings appear more
significant than they actually are.</p>
<p>The “<strong>Durbin-Watson Test</strong>” can be used as a test of
independence of errors (test of autocorrelation).</p>
<ul>
<li><p>The null hypothesis, H<sub>0</sub>, is that there is no
autocorrelation</p></li>
<li><p>The alternative hypothesis, H<sub>a</sub>, is that there is
autocorrelation</p></li>
</ul>
<p>If the p-value is greater than 0.05 then there is no evidence to
reject the null hypothesis that “there is no autocorrelation”. The
results below show a p-value of 0.1573, therefore, the test of
independence of errors around the regression line passes.</p>
<pre class="r"><code>pacman::p_load(&quot;lmtest&quot;)
dwtest(slr_test)</code></pre>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  slr_test
## DW = 1.9104, p-value = 0.1573
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
<div id="test-of-normality" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> <u><strong>Test of
Normality</strong></u></h2>
<p>The test of normality assesses whether the residuals are normally
distributed, i.e., most residuals (errors) are close to zero and large
errors are rare. A Q-Q plot can be used to conduct the test of
normality.</p>
<p>A Q-Q plot is a scatterplot of the quantiles of the residuals against
the quantiles of a normal distribution. Quantiles are statistical values
that divide a dataset or probability distribution into equal-sized
intervals. They help in understanding how data is distributed by marking
specific points that separate the data into groups of equal size.
Examples of quantiles include: quartiles (4 equal parts), percentiles
(100 equal parts), deciles (10 equal parts), etc.</p>
<p>If the points in the Q-Q plot fall along a straight line, then the
normality assumption is satisfied. If the points in the Q-Q plot do not
fall along a straight line, then the normality assumption is not
satisfied.</p>
<pre class="r"><code>plot(slr_test, which = 2)</code></pre>
<p><img
src="1_simple_linear_regression_files/figure-html/test_of_normality-1.png" /><!-- --></p>
</div>
<div id="test-of-homoscedasticity" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> <u><strong>Test of
Homoscedasticity</strong></u></h2>
<p>Homoscedasticity requires that the spread of residuals should be
constant across all levels of the independent variable. A scale-location
plot (a.k.a. spread-location plot) can be used to conduct a test of
homoscedasticity.</p>
<p>The x-axis shows the fitted (predicted) values from the model and the
y-axis shows the square root of the standardized residuals. The red line
is added to help visualize any patterns.</p>
<p>In a model with homoscedastic errors (equal variance across all
predicted values):</p>
<ul>
<li><p>Points should be randomly scattered around a horizontal
line</p></li>
<li><p>The smooth line should be approximately horizontal</p></li>
<li><p>The vertical spread of points should be roughly equal across all
fitted values</p></li>
<li><p>No obvious patterns, funnels, or trends should be
visible</p></li>
</ul>
<p>Points forming a cone shape that widens from left to right suggests
heteroscedasticity with increasing variance for larger fitted
values.</p>
<pre class="r"><code>plot(slr_test, which = 3)</code></pre>
<p><img
src="1_simple_linear_regression_files/figure-html/test_of_homoscedasticity-1.png" /><!-- --></p>
</div>
<div id="quantitative-validation-of-assumptions" class="section level2"
number="4.5">
<h2><span class="header-section-number">4.5</span>
<u><strong>Quantitative Validation of Assumptions</strong></u></h2>
<p>The graphical representations of the various tests of assumptions
should be accompanied by quantitative values. The <code>gvlma</code>
package (Global Validation of Linear Models Assumptions) is useful for
this purpose.</p>
<pre class="r"><code>pacman::p_load(&quot;gvlma&quot;)
gvlma_results &lt;- gvlma(slr_test)
summary(gvlma_results)</code></pre>
<pre><code>## 
## Call:
## lm(formula = customer_lifetime_value ~ purchase_frequency, data = clv_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -19.1176  -5.6169  -0.0491   5.6618  20.4837 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         52.2538     0.9042   57.79   &lt;2e-16 ***
## purchase_frequency  19.5356     0.1700  114.91   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.734 on 498 degrees of freedom
## Multiple R-squared:  0.9637, Adjusted R-squared:  0.9636 
## F-statistic: 1.32e+04 on 1 and 498 DF,  p-value: &lt; 2.2e-16
## 
## 
## ASSESSMENT OF THE LINEAR MODEL ASSUMPTIONS
## USING THE GLOBAL TEST ON 4 DEGREES-OF-FREEDOM:
## Level of Significance =  0.05 
## 
## Call:
##  gvlma(x = slr_test) 
## 
##                      Value p-value                Decision
## Global Stat        5.08943 0.27824 Assumptions acceptable.
## Skewness           0.03973 0.84201 Assumptions acceptable.
## Kurtosis           3.61252 0.05735 Assumptions acceptable.
## Link Function      0.01459 0.90385 Assumptions acceptable.
## Heteroscedasticity 1.42258 0.23298 Assumptions acceptable.</code></pre>
</div>
</div>
<div id="interpret-the-results" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Interpret the
Results</h1>
<p>We can interpret the results of the statistical test with more
confidence if the tests of assumptions are successful.</p>
<div id="academic-statement" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Academic
Statement</h2>
<p>A simple linear regression was conducted to examine the relationship
between customer lifetime value (CLV) and purchase frequency. The
results indicated that purchase frequency significantly predicted CLV, β
= 19.54, SE = 0.17, t(498) = 114.91, p &lt; .001. The model explained
96.37% of the variance in CLV (R2=0.9637, F(1, 498) = 13,200, p &lt;
.001). For every one-unit increase in purchase frequency, CLV increased
by approximately 19.54 units. The residual standard error was 7.73,
indicating strong predictive accuracy.</p>
</div>
<div id="business-analysis" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Business
Analysis</h2>
<p>The strength of the relationship highlights the critical importance
of customer retention. Initiatives that effectively encourage repeat
purchases appear to be a primary driver of customer lifetime value based
on this analysis. This understanding can guide the allocation of
resources towards strategies that foster customer loyalty and encourage
repeat business.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
